### PR TITLE
Fix invalid conversion errors on OE builds

### PR DESCRIPTION
**Pull request by zoltan-ongithub**
Signed-off-by: Zoltan Kuscsik zoltan.kuscsik@linaro.org

### CODE REVIEW

**Comment by jimlawton** [comment]
Hi Zoltan, this repo is a mirror of the Gerrit master at https://code.rdkcentral.com/r/#/admin/projects/components/opensource/westeros. Can you push your change there please?

**Comment by zoltan-ongithub** [comment]
Hi @jimlawton,

  I tried to registers on the page. The registration/activation was successful but it doesn't allow me to login to the page. I tried to do a password recovery, if that helps - but no recovery link was sent out...

**Comment by jimlawton** [comment]
Hi @kuscsik, I've contacted the sysadmins and asked them to check your account.

**Comment by zoltan-ongithub** [comment]
@jimlawton thanks for the help :)

**Pull request closed without merging**
